version: '3.8'

services:
  app:
    build: .
    container_name: todos-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:todosdb;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      JWT_EXPIRATION: 300000
    restart: on-failure

